fragment SettingsParts on Settings {
  __typename
  siteTitle
  tagline
  logo
  theme
  contactEmail
}

fragment PageParts on Page {
  __typename
  title
  navLabel
  order
  showInNav
  blocks {
    __typename
    ... on PageBlocksSplitSection {
      title
      body
      image
      imageSide
      imageSize
      buttons {
        __typename
        label
        url
        status
      }
      showHomeButton
    }
    ... on PageBlocksStackedSection {
      title
      body
      buttons {
        __typename
        label
        url
        status
      }
      showHomeButton
    }
    ... on PageBlocksServiceCard {
      title
      description
      image
      imageSide
      imageSize
      status
      bookingOptions {
        __typename
        label
        bookUrl
        note
        addOns {
          __typename
          service
          bookUrl
        }
      }
      showHomeButton
    }
    ... on PageBlocksCardGrid {
      title
      cards {
        __typename
        title
        description
        buttonLabel
        buttonUrl
      }
      showHomeButton
    }
    ... on PageBlocksValuesSection {
      title
      words
      showHomeButton
    }
    ... on PageBlocksEventSection {
      title
      body
      images
      buttons {
        __typename
        label
        url
        status
      }
      showHomeButton
    }
  }
}
